version: '3.4'

services:
  bank.apigateway:
    image: ${DOCKER_REGISTRY-}bank.apigateway
    container_name: ${DOCKER_REGISTRY-}bank.apigateway
    build:
      context: .
      dockerfile: Bank.ApiGateway/Dockerfile
    links:
        - bank.auth.api
        - bank.loans.api
    depends_on:
        - bank.auth.api
        - bank.loans.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4000
    ports:
      - "4000:4000"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  bank.auth.api:
    image: ${DOCKER_REGISTRY-}bank.auth.api
    container_name: ${DOCKER_REGISTRY-}bank.auth.api
    hostname: bank.auth.api
    build:
      context: .
      dockerfile: Bank.Auth.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4001
    ports:
      - "4001:4001"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  bank.loans.api:
    image: ${DOCKER_REGISTRY-}bank.loans.api
    container_name: ${DOCKER_REGISTRY-}bank.loans.api
    hostname: bank.loans.api
    build:
      context: .
      dockerfile: Bank.Loans.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4002
    ports:
      - "4002:4002"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro