name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Restore dependencies
      run: dotnet restore Bank.Loans.Api/Bank.Loans.Api.csproj

    - name: Build
      run: dotnet build Bank.Loans.Api/Bank.Loans.Api.csproj --no-restore

    - name: Test
      run: dotnet test Bank.Loans.Api/Bank.Loans.Api.csproj --no-build --verbosity normal

    - name: Publish
      run: dotnet publish Bank.Loans.Api/Bank.Loans.Api.csproj -c Release -o Bank.Loans.Api/publish

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: bank-loans-api
        path: Bank.Loans.Api/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: bank-loans-api

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bank-loans-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d56e05157a294288bdda0ea2e370729d }}
        package: .
